import { Inter } from "next/font/google";
import Navbar from "./component/common/navbar"
import "../../app/globals.css"
import Footer from "./component/common/footer.jsx"
import { defaultLocale, locales } from "@/config";
import { notFound } from "next/navigation";
import { NextIntlClientProvider, useMessages } from "next-intl";


const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps(context) {
  // Get the language from the request headers
  const language = context.req.headers['accept-language'];
  context.res.setHeader('Set-Cookie', `language=${language}; Path=/; HttpOnly`);
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, language })  {
  if (!locales.includes(defaultLocale)) notFound();
  const messages = useMessages();

  return (
    <html lang={language}>
      <body className={inter.className}>
      <NextIntlClientProvider messages={messages}>
        <Navbar/>
        {children}
        <Footer/>
        </NextIntlClientProvider>
        </body>
    </html>
  );
}
